[package]
name = "arrow_bug_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "arrow_bug_demo"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "32.0.0", features = ["pyarrow"]}
pyo3 = { version = "0.18.0", features = ["extension-module"] }

[dev-dependencies]
parquet = "32.0.0"
