name: ci

on:
  push:

jobs:
  linux:
    name: demo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run
        run: |
          python -m pip install -e .
          python test_demo.py
