on:
  push: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: x86_64
          maturin-version: "v0.14.0"
          args: --out dist
      - name: Run Cargo test
        run: cargo test -- --nocapture
      - name: Run Python test
        run: |
          pip install dist/arrow_bug_demo*.whl --force-reinstall
          RUST_BACKTRACE=full python test.py
